#!/usr/bin/env node
import { createInterface } from "node:readline";
import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { execSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { CookieExtractor } from "./clients/cookie-extractor.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const ENV_PATH = path.resolve(ROOT, ".env");
const AUTH_DIR = path.resolve(ROOT, ".auth");
const COOKIES_PATH = path.resolve(AUTH_DIR, "cookies.json");

const rl = createInterface({ input: process.stdin, output: process.stderr });

function ask(question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()));
  });
}

function openUrl(url: string): void {
  // Always print the URL so it's visible and clickable in terminals
  console.error("");
  console.error(`  → ${url}`);
  console.error("");

  const cmd =
    process.platform === "darwin"
      ? "open"
      : process.platform === "win32"
        ? "start"
        : "xdg-open";
  try {
    execSync(`${cmd} "${url}"`, { stdio: "ignore", timeout: 5000 });
  } catch {
    // Browser didn't open — URL is already printed above
  }
}

function loadEnv(): Record<string, string> {
  const env: Record<string, string> = {};
  if (existsSync(ENV_PATH)) {
    const content = readFileSync(ENV_PATH, "utf-8");
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx === -1) continue;
      env[trimmed.slice(0, eqIdx)] = trimmed.slice(eqIdx + 1);
    }
  }
  return env;
}

function saveEnv(env: Record<string, string>): void {
  const lines = [
    "# CurseForge MCP Server Configuration",
    "# Generated by: npm run setup",
    "",
    `CURSEFORGE_API_KEY=${env.CURSEFORGE_API_KEY || ""}`,
    `CURSEFORGE_AUTHOR_TOKEN=${env.CURSEFORGE_AUTHOR_TOKEN || ""}`,
    `CURSEFORGE_GAME_SLUG=${env.CURSEFORGE_GAME_SLUG || ""}`,
    "",
  ];
  writeFileSync(ENV_PATH, lines.join("\n"));
}

// ── Main ──────────────────────────────────────────────────────────

async function main() {
  console.error("");
  console.error("╔══════════════════════════════════════════════════╗");
  console.error("║     CurseForge MCP Server — Setup               ║");
  console.error("╚══════════════════════════════════════════════════╝");
  console.error("");

  const env = loadEnv();

  // ── Step 1: Cookies (automatic) ─────────────────────────────────
  await stepCookies();

  // ── Step 2: Core API Key ────────────────────────────────────────
  await stepApiKey(env);

  // ── Step 3: Author Token (optional) ─────────────────────────────
  await stepAuthorToken(env);

  // ── Save and summarize ──────────────────────────────────────────
  saveEnv(env);
  console.error("");
  console.error("━━━ Building server... ━━━");
  console.error("");
  try {
    execSync("npm run build", { cwd: ROOT, stdio: "inherit" });
    console.error("");
    console.error("━━━ Done! ━━━");
  } catch {
    console.error("");
    console.error("  ✗ Build failed. Run 'npm run build' manually to see errors.");
  }
  console.error("");
  printStatus(env);
  console.error("");
  console.error("  Restart your AI client (Claude Code, Cursor, etc.) to activate.");
  console.error("");

  rl.close();
}

// ── Step 1: Auto-extract cookies ──────────────────────────────────

async function stepCookies() {
  console.error("━━━ Step 1/3: Session Cookies ━━━");
  console.error("");

  // Try automatic extraction first
  console.error("  Extracting cookies from your browser automatically...");
  const extractor = new CookieExtractor();
  const result = await extractor.extractCookies();

  if (result.cookies.length > 0) {
    // Save cookies
    if (!existsSync(AUTH_DIR)) {
      mkdirSync(AUTH_DIR, { recursive: true });
    }
    writeFileSync(COOKIES_PATH, JSON.stringify(result.cookies, null, 2));
    console.error(`  ✓ ${result.cookies.length} cookies extracted from ${result.browser}`);
    console.error("");
    return;
  }

  // Auto-extraction failed — guide user to log in
  console.error("  ✗ No CurseForge cookies found in any browser.");
  console.error("  Please log in to CurseForge in your browser:");
  openUrl("https://www.curseforge.com");
  await ask("  Press Enter after you've logged in... ");
  console.error("");

  // Retry extraction
  console.error("  Retrying cookie extraction...");
  const retry = await extractor.extractCookies();
  if (retry.cookies.length > 0) {
    if (!existsSync(AUTH_DIR)) {
      mkdirSync(AUTH_DIR, { recursive: true });
    }
    writeFileSync(COOKIES_PATH, JSON.stringify(retry.cookies, null, 2));
    console.error(`  ✓ ${retry.cookies.length} cookies extracted from ${retry.browser}`);
  } else {
    console.error("  ✗ Still no cookies. Web API tools (comments, analytics) will be unavailable.");
    console.error("    You can use the cf_auto_extract_cookies tool later to retry.");
  }
  console.error("");
}

// ── Step 2: Core API Key ──────────────────────────────────────────

async function stepApiKey(env: Record<string, string>) {
  console.error("━━━ Step 2/3: Core API Key (for search, download, mod details) ━━━");
  console.error("");

  if (env.CURSEFORGE_API_KEY) {
    console.error(`  ✓ Already configured: ${env.CURSEFORGE_API_KEY.slice(0, 8)}...`);
    const update = await ask("  Update it? (y/N): ");
    if (update.toLowerCase() !== "y") {
      console.error("");
      return;
    }
  }

  console.error("  Open the API Keys page:");
  openUrl("https://console.curseforge.com/#/api-keys");
  console.error("  Then:");
  console.error("    1. Sign up / log in (if needed)");
  console.error("    2. Create Organization + Project (if you don't have one)");
  console.error("    3. Click Generate API Key → copy it");
  console.error("");

  const apiKey = await ask("  Paste your API Key here (or Enter to skip): ");
  if (apiKey) {
    env.CURSEFORGE_API_KEY = apiKey;
    console.error("  ✓ API Key saved");
  } else {
    console.error("  → Skipped. search_mods, download_mod and other Core API tools will be disabled.");
  }
  console.error("");
}

// ── Step 3: Author Token ──────────────────────────────────────────

async function stepAuthorToken(env: Record<string, string>) {
  console.error("━━━ Step 3/3: Author Token (for uploading mods — optional) ━━━");
  console.error("");

  if (env.CURSEFORGE_AUTHOR_TOKEN) {
    console.error(`  ✓ Already configured: ${env.CURSEFORGE_AUTHOR_TOKEN.slice(0, 8)}...`);
    const update = await ask("  Update it? (y/N): ");
    if (update.toLowerCase() !== "y") {
      console.error("");
      return;
    }
  }

  const want = await ask("  Do you upload mods to CurseForge? (y/N): ");
  if (want.toLowerCase() !== "y") {
    console.error("  → Skipped. You can run setup again later if needed.");
    console.error("");
    return;
  }

  console.error("");
  console.error("  Open the API Tokens page:");
  openUrl("https://www.curseforge.com/account/api-tokens");
  console.error("  Then:");
  console.error("    1. Log in if needed");
  console.error("    2. Click 'Generate Token' or copy an existing one");
  console.error("");

  const token = await ask("  Paste your Author Token here (or Enter to skip): ");
  if (token) {
    env.CURSEFORGE_AUTHOR_TOKEN = token;
    console.error("  ✓ Author Token saved");
  } else {
    console.error("  → Skipped. Upload tools will be disabled.");
  }
  console.error("");
}

// ── Status summary ────────────────────────────────────────────────

function printStatus(env: Record<string, string>) {
  const cookiesOk = existsSync(COOKIES_PATH);
  const apiKeyOk = !!env.CURSEFORGE_API_KEY;
  const tokenOk = !!env.CURSEFORGE_AUTHOR_TOKEN;

  console.error("  Status:");
  console.error(
    `  ${cookiesOk ? "✓" : "✗"} Cookies       → comments, analytics, project settings`,
  );
  console.error(
    `  ${apiKeyOk ? "✓" : "✗"} Core API Key  → search, download, mod details, categories`,
  );
  console.error(
    `  ${tokenOk ? "✓" : "✗"} Author Token  → upload mod files`,
  );

  // CFWidget (2) always + cookies web tools (9) + api key core tools (12) + author upload (4)
  const toolCount =
    2 + (cookiesOk ? 9 : 0) + (apiKeyOk ? 12 : 0) + (tokenOk ? 4 : 0);
  console.error("");
  console.error(`  Tools available: ${toolCount}/27`);
}

main().catch((err) => {
  console.error("Error:", err);
  rl.close();
  process.exit(1);
});
