#!/usr/bin/env node
import { createInterface } from "node:readline";
import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { execSync, execFileSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { CookieExtractor } from "./clients/cookie-extractor.js";
import { WebClient } from "./clients/web-client.js";
import { loadConfig } from "./config.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const ENV_PATH = path.resolve(ROOT, ".env");
const AUTH_DIR = path.resolve(ROOT, ".auth");
const COOKIES_PATH = path.resolve(AUTH_DIR, "cookies.json");

const rl = createInterface({ input: process.stdin, output: process.stderr });

function ask(question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()));
  });
}

function openUrl(url: string): void {
  // Always print the URL so it's visible and clickable in terminals
  console.error("");
  console.error(`  → ${url}`);
  console.error("");

  // Open the default browser, passing the URL as a separate argv element (no shell
  // string). On Windows the URL must go through `cmd /c start "" "<url>"`: `start`
  // treats the first quoted token as the window TITLE, so the empty "" title is
  // required — otherwise an empty console window opens and the browser does not.
  try {
    if (process.platform === "darwin") {
      execFileSync("open", [url], { stdio: "ignore", timeout: 5000 });
    } else if (process.platform === "win32") {
      execFileSync("cmd", ["/c", "start", "", url], {
        stdio: "ignore",
        timeout: 5000,
        windowsHide: true,
      });
    } else {
      execFileSync("xdg-open", [url], { stdio: "ignore", timeout: 5000 });
    }
  } catch {
    // Browser didn't open — URL is already printed above
  }
}

function loadEnv(): Record<string, string> {
  const env: Record<string, string> = {};
  if (existsSync(ENV_PATH)) {
    const content = readFileSync(ENV_PATH, "utf-8");
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx === -1) continue;
      env[trimmed.slice(0, eqIdx)] = trimmed.slice(eqIdx + 1);
    }
  }
  return env;
}

function saveEnv(env: Record<string, string>): void {
  const lines = [
    "# CurseForge MCP Server Configuration",
    "# Generated by: npm run setup",
    "",
    `CURSEFORGE_API_KEY=${env.CURSEFORGE_API_KEY || ""}`,
    `CURSEFORGE_AUTHOR_TOKEN=${env.CURSEFORGE_AUTHOR_TOKEN || ""}`,
    "",
  ];
  writeFileSync(ENV_PATH, lines.join("\n"));
}

// ── Main ──────────────────────────────────────────────────────────

async function main() {
  console.error("");
  console.error("╔══════════════════════════════════════════════════╗");
  console.error("║     CurseForge MCP Server — Setup               ║");
  console.error("╚══════════════════════════════════════════════════╝");
  console.error("");

  const env = loadEnv();

  // ── Step 1: Cookies (automatic) ─────────────────────────────────
  await stepCookies();

  // ── Step 2: Core API Key ────────────────────────────────────────
  await stepApiKey(env);

  // ── Step 3: Author Token (optional) ─────────────────────────────
  await stepAuthorToken(env);

  // ── Save and summarize ──────────────────────────────────────────
  saveEnv(env);
  console.error("");
  // The package ships prebuilt (npm `prepare` runs tsc on install), and npx
  // prunes devDependencies afterwards, so `tsc` is usually gone by now. Only
  // build if the compiled entry is actually missing, and tolerate a missing tsc.
  const builtEntry = path.join(ROOT, "build", "index.js");
  if (existsSync(builtEntry)) {
    console.error("━━━ Done! (server already built) ━━━");
  } else {
    console.error("━━━ Building server... ━━━");
    console.error("");
    try {
      execSync("npm run build", { cwd: ROOT, stdio: "inherit" });
      console.error("");
      console.error("━━━ Done! ━━━");
    } catch {
      console.error("");
      console.error("  ⚠ Could not build (tsc not available in this context).");
      console.error("    If the server fails to start, run 'npm run build' in the project dir.");
    }
  }
  console.error("");
  printStatus(env);
  console.error("");
  console.error("  Restart your AI client (Claude Code, Cursor, etc.) to activate.");
  console.error("");

  rl.close();
}

// ── Step 1: Auto-extract cookies ──────────────────────────────────

async function stepCookies() {
  console.error("━━━ Step 1/3: Session Cookies (Web API tools) ━━━");
  console.error("");
  console.error("  Web API tools (comments, project settings, descriptions) are NOT");
  console.error("  available through CurseForge's official API. They rely on an");
  console.error("  UNOFFICIAL workaround:");
  console.error("    • the server reads your CurseForge session cookies from your browser,");
  console.error("      and/or drives a dedicated browser window to bypass Cloudflare;");
  console.error("    • this is not endorsed by CurseForge and may break if their site changes.");
  console.error("");
  console.error("  Core API (search/download) and Upload tools do NOT need this and work natively.");
  console.error("");

  const consent = (await ask("  Enable Web API tools via this workaround? (y/N): ")).toLowerCase();
  if (consent !== "y" && consent !== "yes") {
    console.error("");
    console.error("  Skipped. Web API tools (comments/settings/description) will be unavailable.");
    console.error("  You can enable them later with the cf_auto_extract_cookies / cf_set_cookies tools.");
    console.error("");
    return;
  }
  console.error("");

  // Try automatic extraction first
  console.error("  Extracting cookies from your browser automatically...");
  const extractor = new CookieExtractor();
  const result = await extractor.extractCookies();

  if (result.cookies.length > 0) {
    // Save cookies
    if (!existsSync(AUTH_DIR)) {
      mkdirSync(AUTH_DIR, { recursive: true });
    }
    writeFileSync(COOKIES_PATH, JSON.stringify(result.cookies, null, 2));
    console.error(`  ✓ ${result.cookies.length} cookies extracted from ${result.browser}`);
    console.error("");
    return;
  }

  // Auto-extraction found nothing — this is normal on Windows Chrome 127+, whose
  // App-Bound Encryption blocks reading cookies out of the user's own profile.
  // Fall back to a one-time interactive login in the dedicated bundled browser:
  // it works on any OS, and the persistent profile remembers it for future runs.
  console.error("  ✗ Automatic extraction found no CurseForge session.");
  console.error("    (Normal on Windows Chrome 127+ due to App-Bound Encryption.)");
  console.error("    A one-time login in a dedicated browser is the reliable cross-OS way.");
  console.error("");

  const yn = (await ask("  Log in once in a dedicated browser now? It's remembered for future runs. (Y/n): ")).toLowerCase();
  if (yn.startsWith("n")) {
    console.error("");
    console.error("  Skipped. Web API tools (comments/settings/description) will be unavailable.");
    console.error("  Enable them later with the cf_auto_extract_cookies / cf_set_cookies tools.");
    console.error("");
    return;
  }
  console.error("");

  // Ensure the bundled browser is installed (one-time ~110MB download on first run;
  // instant if already cached). Output is captured to hide playwright's noisy
  // "run npm install" warning; on failure we continue — the launch below surfaces
  // a clearer, actionable error.
  console.error("  Preparing browser (one-time ~110MB download on first run; may take a minute)...");
  try {
    execSync("npx patchright install chromium", { cwd: ROOT, stdio: "pipe" });
    console.error("  ✓ Browser ready.");
  } catch {
    console.error("  ⚠ Could not pre-install the bundled browser; will try launching anyway.");
  }
  console.error("");

  const web = new WebClient(loadConfig());
  try {
    console.error("  A browser window will open — log in to CurseForge (you can save the password). Capturing your session...");
    const ok = await web.loginInteractive();
    if (ok) console.error("  ✓ Logged in — session saved. Future runs are automatic.");
    else console.error("  ✗ Login timed out. You can retry later with the cf_auto_extract_cookies tool, or cf_set_cookies.");
  } catch (e) {
    console.error("  ✗ Could not open the login browser: " + (e instanceof Error ? e.message : e));
    console.error("    Run 'npx patchright install chromium', then retry, or use cf_set_cookies.");
  } finally {
    await web.close();
  }
  console.error("");
}

// ── Step 2: Core API Key ──────────────────────────────────────────

async function stepApiKey(env: Record<string, string>) {
  console.error("━━━ Step 2/3: Core API Key (for search, download, mod details) ━━━");
  console.error("");

  if (env.CURSEFORGE_API_KEY) {
    console.error(`  ✓ Already configured: ${env.CURSEFORGE_API_KEY.slice(0, 8)}...`);
    const update = await ask("  Update it? (y/N): ");
    if (update.toLowerCase() !== "y") {
      console.error("");
      return;
    }
  }

  console.error("  Open the API Keys page:");
  openUrl("https://console.curseforge.com/#/api-keys");
  console.error("  Then:");
  console.error("    1. Sign up / log in (if needed)");
  console.error("    2. Create Organization + Project (if you don't have one)");
  console.error("    3. Click Generate API Key → copy it");
  console.error("");

  const apiKey = await ask("  Paste your API Key here (or Enter to skip): ");
  if (apiKey) {
    env.CURSEFORGE_API_KEY = apiKey;
    console.error("  ✓ API Key saved");
  } else {
    console.error("  → Skipped. search_mods, download_mod and other Core API tools will be disabled.");
  }
  console.error("");
}

// ── Step 3: Author Token ──────────────────────────────────────────

async function stepAuthorToken(env: Record<string, string>) {
  console.error("━━━ Step 3/3: Author Token (for uploading mods — optional) ━━━");
  console.error("");

  if (env.CURSEFORGE_AUTHOR_TOKEN) {
    console.error(`  ✓ Already configured: ${env.CURSEFORGE_AUTHOR_TOKEN.slice(0, 8)}...`);
    const update = await ask("  Update it? (y/N): ");
    if (update.toLowerCase() !== "y") {
      console.error("");
      return;
    }
  }

  const want = await ask("  Do you upload mods to CurseForge? (y/N): ");
  if (want.toLowerCase() !== "y") {
    console.error("  → Skipped. You can run setup again later if needed.");
    console.error("");
    return;
  }

  console.error("");
  console.error("  Open the API Tokens page:");
  openUrl("https://www.curseforge.com/account/api-tokens");
  console.error("  Then:");
  console.error("    1. Log in if needed");
  console.error("    2. Click 'Generate Token' or copy an existing one");
  console.error("");

  const token = await ask("  Paste your Author Token here (or Enter to skip): ");
  if (token) {
    env.CURSEFORGE_AUTHOR_TOKEN = token;
    console.error("  ✓ Author Token saved");
  } else {
    console.error("  → Skipped. Upload tools will be disabled.");
  }
  console.error("");
}

// ── Status summary ────────────────────────────────────────────────

function printStatus(env: Record<string, string>) {
  const cookiesOk = existsSync(COOKIES_PATH);
  const apiKeyOk = !!env.CURSEFORGE_API_KEY;
  const tokenOk = !!env.CURSEFORGE_AUTHOR_TOKEN;

  console.error("  Status:");
  console.error(
    `  ${cookiesOk ? "✓" : "✗"} Cookies       → comments, analytics, project settings`,
  );
  console.error(
    `  ${apiKeyOk ? "✓" : "✗"} Core API Key  → search, download, mod details, categories`,
  );
  console.error(
    `  ${tokenOk ? "✓" : "✗"} Author Token  → upload mod files`,
  );

  // CFWidget (2) always + cookies web tools (8) + api key core tools (12) + author upload (3)
  const toolCount =
    2 + (cookiesOk ? 8 : 0) + (apiKeyOk ? 12 : 0) + (tokenOk ? 3 : 0);
  console.error("");
  console.error(`  Tools available: ${toolCount}/25`);
}

main().catch((err) => {
  console.error("Error:", err);
  rl.close();
  process.exit(1);
});
